language: python
python:
- '3.5'
script:
- touch foo
deploy:
  provider: pypi
  user: grantstephens
  password:
    secure: aqGcLTHdkzLNi9hieuUepQb4Oq3Do/t6v5bpbQyIq+GUh5RVg3hO1RoHlwlAdbaMhjsnoyWK4lW8rLYAVfYgYw7jRU6s1Kj73mtg3CU/pG4DE5y34Rmt7h4ck5katKDvDZa4zM+EJ7v+22CeNzNN+qB3DFqljmHdqkzONsstUONPy16UCej0FpDMIwwm03blmgahTHFKQCXx1fMsFvLW0zv+yIvqdPP05NZj9bfaLvVLyj32/rk0PWVvaJJ6upf095HYNjGijXQFR0Lnu4G4l1arvl1YrG2rF/lKDX9L6XKywq9FfmdDRAfsNpsuwy0+FNdRyHkKItHmUBkSDaKzfEu0mIxeYQFQw6kS+c/S12+eOyAP5FdmEgeW84Lq4if5Zwh1m311jPnSauUL+JlKIxIdM8h3CmPVq/b2LmBxleyn/hGaeMGpzPecZgb7BXC270f6zJV7cBRk0Zh2EOUVvUWPtJRQwge5fuQLGDex6A2c2ktUcX4noh4F203RWlVYnRkkBGpgnNdYxmaMkuirrhJNrgUIcPOpVc1BWcnplxlED2b9rZta1Q4+h3QZ0ceeLvomTpjJm8y1CUbnnXFFxwhfGsNJCZEEQFTeVpJ3voM7rdG9VAnKpdI87Xnx+NUUxGrpfDTkXifSrv6hVTscm/X6JQH+WmVTx87SNRZ5LJM=
  on:
    tags: true
    branch: master
